# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Set zsh default shell
set-option -g default-shell /bin/zsh

# Use C-a for command prefix
set-option -g prefix C-a
unbind-key C-b
bind-key C-a send-prefix

# Use 256 color terminal
set -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",*256col*:Tc"

# Enable mouse support for switching panes/windows
setw -g mouse on

# Command delay? We don't want that, make it short
set -sg escape-time 1

# Starting window index
set -g base-index 1

# Starting pane index
setw -g pane-base-index 1

# Use hjkl to move between panes
bind h select-pane -L
bind l select-pane -R
bind j select-pane -D
bind k select-pane -U

# Use HJKL for resizing panes
bind -r H resize-pane -L 2
bind -r L resize-pane -R 2
bind -r J resize-pane -D 2
bind -r K resize-pane -U 2

# Use the vertical and horizontal symbols to split the screen
bind | split-window -h
bind - split-window -v

# Use vi-like shortcuts
set -g mode-keys vi

# Reload the config file with r
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"

# Status bar customization
set -g status on                                  # Enable status bar
set -g status-interval 5                          # Update every 5 seconds
set -g status-justify left                      # Center-align the status line
# set -g status-bg black                            # Background color
# set -g status-fg white                            # Foreground color
set -g status-style 'bg=#172b2b fg=#5eacd3'

# Left side of the status bar
set -g status-left "#[fg=cyan]mecodes #[fg=white]  "  # Display GitHub username

# Right side of the status bar
# set -g status-right "#[fg=white]#(TZ='Asia/Kolkata' date '+%H:%M') #[fg=cyan]%d-%b-%y #[fg=yellow] #[fg=green]Session: #S"
set -g status-right "#[fg=white]#(env TZ='Asia/Kolkata' date '+%H:%M') #[fg=cyan]%d-%b-%y #[fg=yellow] #[fg=green]Session: #S"

# Middle part (optional, uncomment to add it)
#set -g status-left-length 30
#set -g status-right-length 150

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

